export const SET_ROOMS = 'SET_ROOMS'
export const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM'
export const SET_USER = 'SET_USER'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const ADD_ROOM = 'ADD_ROOM'
